#!/usr/bin/env python3
"""
Results board renderer (v5) — markdown over the JSON stores.

Reads the derived structures from tools/registry.py (single compute
source shared with build_index.py) and renders:

  LEADERBOARD.md     landing: what-this-is, Models (latest activity first
                     — NOT a ranking), Latest tests, model page links
  models/<id>.md     per-model pages: variants, run history, sources, lineage

CLI queries print tables to stdout (no writes):
  python tools/leaderboard.py --sort tg --cap vision --engine vulkan
  python tools/leaderboard.py --min-witnesses 2 --json
  python tools/leaderboard.py --next          # personal gaps, stdout only
"""
import argparse
import json

import registry
from common import REPO_ROOT

registry.MIN_WITNESSES  # noqa: keep module initialized


def caps(row):
    return row.get("capabilities_confirmed") or {}


def fmt_tmv(row):
    c = caps(row)
    return (f"{'Y' if c.get('tools') else '-'}{'Y' if c.get('mcp') else '-'}"
            f"{'Y' if c.get('vision') else '-'}")


def cap_score(row):
    c = caps(row)
    return sum(bool(c.get(k)) for k in ("tools", "mcp", "vision"))


def status_mark(row):
    if row.get("cross_validated"):
        return "validated*"
    if (row.get("witnesses") or 0) >= 1:
        return "1 witness"
    if row.get("status") == "failed":
        return "failed"
    return "no results"


def landing_md(rows, n_runs):
    lines = ["# Strix Halo AI Recipe Registry — results board", "",
             "_Generated by tools/leaderboard.py from immutable result "
             "records — do not hand-edit._", "",
             "## What is this", "",
             "A registry of reproducible, evidence-backed serving recipes for "
             "local LLMs on unified-memory Linux boxes. Every number comes "
             "from an immutable result record — nothing is hand-set, "
             "cross-validation is derived from independent witnesses.",
             "",
             "- **Run your own tests / add a recipe:** read `SKILL.md`; query "
             "the data layer with `tools/registry.py` "
             "(`Store().find(quant=..., backend=...)`).",
             "- **Format & trust model:** `FORMAT.md`. **Licensing:** code "
             "Apache-2.0, registry data CC0, docs CC BY 4.0 (README).", "",
             "> Tables are ordered by latest activity — this is NOT a quality "
             "ranking; there is no universal score. Rank by what you need: "
             "`python tools/leaderboard.py --sort tg --cap vision`.", "",
             "## Models", "",
             f"_{len(rows)} models · {n_runs} result records · latest activity first_", "",
             "| id | model | variants | quant(s) | size | T M V | PP t/s | "
             "TG t/s | wit | backend | verdict |",
             "|---|---|---|---|---|---|---|---|---|---|---|"]
    order = sorted(rows, key=lambda r: (r["last_run"] == "", -len(r["last_run"]),
                                        r["id"]))
    for r in order:
        q = ",".join(str(x) for x in r.get("quants") or []) or "—"
        lines.append(
            f"| [{r['id']}](models/{r['id']}.md) | {r['model_name'][:40]} | "
            f"{r.get('n_variants', 0)} | {q} | {r.get('size_gb') or '-'} | "
            f"{fmt_tmv(r)} | {r.get('pp') or '-'} | {r.get('tg') or '-'} | "
            f"{r.get('witnesses', 0)} | {r.get('backend')} | {status_mark(r)} |")
    lines += ["",
              "_T=confirmed tool calling, M=confirmed MCP, V=confirmed vision. "
              "`validated*` = ≥ 2 contributor ids at the current hash with all "
              "declared tests passing — aliases of one person count as one._", ""]
    return lines


def latest_tests_md(models, limit=10):
    runs = [s for m in models.values() for s in m["runs"]]
    runs.sort(key=lambda x: x.get("run_id", ""), reverse=True)
    lines = ["## Latest tests", "",
             "| when (UTC) | model | test | result | PP t/s | TG t/s | who |",
             "|---|---|---|---|---|---|---|"]
    for s in runs[:limit]:
        rid = s.get("model_id") or "?"
        ts = (s.get("ts") or "")[:8] + " " + (s.get("ts") or "")[8:] if s.get("ts") else "?"
        for t in s.get("tests", []):
            lines.append(f"| {ts} | [{rid}](models/{rid}.md) | `{t['id']}` | "
                         f"{t.get('result')} | {s.get('pp') or '-'} | "
                         f"{s.get('tg') or '-'} | {s.get('contributor_id')} |")
    return lines


def model_md(rid, row, doc):
    recipe = doc["recipe"]
    lines = [f"# {recipe['model']['name']} (`{rid}`)", "",
             f"- Latest version: **v{row['version']}** · "
             f"{recipe.get('quant') or '?'} · {recipe['model'].get('size_gb')} GB · "
             f"arch {recipe['model'].get('arch')} · engine {row.get('backend')}",
             f"- Source: {recipe['model'].get('source') or '—'}",
             f"- Verdict: {status_mark(row)} — {doc['counts']['results']} result(s) "
             f"across {row.get('n_variants', 0)} variant(s); "
             f"{row.get('witnesses', 0)} witness(es) at the current hash",
             f"- Confirmed capabilities: tools={caps(row).get('tools')}, "
             f"mcp={caps(row).get('mcp')}, vision={caps(row).get('vision')} · "
             f"objectives: {', '.join(row.get('objectives_primary') or []) or '—'}",
             "",
             "## Variants (configurations tested)", "",
             "Each variant = a content hash (pinned launch configuration) "
             "with its own evidence trail. Quants are a dimension under a "
             "configuration.", "",
             "| hash | v | quant(s) | PP t/s | TG t/s | wit | results | tests (pass/total) |",
             "|---|---|---|---|---|---|---|---|"]
    for v in doc["variants"]:
        q = ",".join(str(x) for x in v["quant"]) or "—"
        tallies = []
        for tid, tally in v["tests"].items():
            total = sum(tally.values())
            tallies.append(f"{tid} {tally.get('pass', 0)}/{total}")
        lines.append(f"| `{v['hash']}` | v{v['version']} | {q} | "
                     f"{v['pp'] or '-'} | {v['tg'] or '-'} | {v['witnesses']} "
                     f"| {v['results']} | {'; '.join(tallies) or '—'} |")
    lines += ["", "## Runs", "",
              "| run (UTC) | contributor | quant | hash | PP | TG | tests |",
              "|---|---|---|---|---|---|---|"]
    for s in doc["runs"]:
        ts = s.get("ts") or "?"
        tsum = "; ".join(f"{t['id']}={t['result']}" for t in s.get("tests", []))
        lines.append(f"| {ts} | {s.get('contributor_id')} | {s.get('quant') or '-'} "
                     f"| `{s.get('hash')}` | {s.get('pp') or '-'} | "
                     f"{s.get('tg') or '-'} | {tsum} |")
    notes = [(s.get("ts"), s.get("notes")) for s in doc["runs"] if s.get("notes")]
    if notes:
        lines += ["", "### Sources & notes", ""]
        for ts, n in notes:
            lines.append(f"- {ts}Z — {n}")
    lineage = recipe.get("lineage", {}).get("parents", [])
    if lineage:
        lines += ["", "### Lineage", ""]
        for p in lineage:
            lines.append(f"- **{p['id']} v{p.get('version')}** — "
                         f"{p.get('contribution', '')}")
        if recipe.get("lineage", {}).get("rationale"):
            lines.append(f"- Rationale: {recipe['lineage']['rationale']}")
    return "\n".join(lines) + "\n"


def render_table(rows):
    order = sorted(rows, key=lambda r: (-cap_score(r), -(r.get("witnesses") or 0),
                                        -(r.get("tg") or 0)))
    print("{:<20} {:<9} {:>5} {:>8} {:>8} {:>3} {:>7}  {}".format(
        "id", "quant", "TMV", "PP", "TG", "wit", "backend", "model"))
    for r in order:
        print("{:<20} {:<9} {:>5} {:>8} {:>8} {:>3} {:>7}  {}".format(
            r["id"][:20], ",".join(str(q) for q in r.get("quants") or [])[:9],
            fmt_tmv(r), r.get("pp") or "-", r.get("tg") or "-",
            r.get("witnesses", 0), r.get("backend"), r.get("model_name")[:32]))
    print("\nQuery convenience only — order changes with --sort; see "
          "LEADERBOARD.md for the neutral board.")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sort", choices=["score", "tg", "pp", "witnesses",
                                       "name"], default="score")
    ap.add_argument("--reverse", action="store_true")
    ap.add_argument("--engine", choices=["vulkan", "rocm"])
    ap.add_argument("--cap", choices=["tools", "mcp", "vision"])
    ap.add_argument("--min-witnesses", type=int, default=0)
    ap.add_argument("--next", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--no-write", action="store_true")
    args = ap.parse_args()

    rows, models, _runs = registry.compute()

    if args.json:
        print(json.dumps(rows, indent=2, default=str))
        return
    if args.next:
        for i, a in enumerate(registry.Store().next(), 1):
            print(f"{i}. {a}")
        return

    filtered = rows
    if args.engine:
        filtered = [r for r in filtered if args.engine in (r.get("backend") or "")]
    if args.cap:
        filtered = [r for r in filtered if caps(r).get(args.cap)]
    if args.min_witnesses:
        filtered = [r for r in filtered if (r.get("witnesses") or 0) >= args.min_witnesses]
    key = {"score": lambda r: (-cap_score(r), -(r.get("witnesses") or 0), -(r.get("tg") or 0)),
           "tg": lambda r: -(r.get("tg") or 0),
           "pp": lambda r: -(r.get("pp") or 0),
           "witnesses": lambda r: -(r.get("witnesses") or 0),
           "name": lambda r: r["id"]}[args.sort]
    render_table(sorted(filtered, key=key, reverse=args.reverse))

    if not args.no_write:
        n_runs = len(_runs)
        landing = "\n".join(landing_md(rows, n_runs) + latest_tests_md(models)) + "\n"
        with open(REPO_ROOT / "LEADERBOARD.md", "w") as f:
            f.write(landing)
        outdir = REPO_ROOT / "models"
        outdir.mkdir(exist_ok=True)
        for rid, doc in models.items():
            row = next(x for x in rows if x["id"] == rid)
            with open(outdir / f"{rid}.md", "w") as f:
                f.write(model_md(rid, row, doc))
        print(f"\nWrote LEADERBOARD.md + {len(models)} model page(s) under models/")


if __name__ == "__main__":
    main()
