#!/usr/bin/env python3
"""
Aggregate results/ into LEADERBOARD.md.

Trust rule (derived, never hand-set): a (recipe_id, content_hash) is
cross-validated only with >= MIN_WITNESSES distinct contributor_ids and
every test the recipe declares has at least one pass among those
witnesses. Aggregates are per-dimension medians — there is NO universal
score; a faster recipe is not automatically better (see data model:
objectives/tradeoffs).

LEADERBOARD.md is generated; do not hand-edit.
"""
import statistics
from collections import defaultdict

from common import REPO_ROOT, iter_recipe_files, iter_result_files, load_yaml

MIN_WITNESSES = 2


def latest_by_id(recipes):
    latest = {}
    for r in recipes:
        cur = latest.get(r["id"])
        if cur is None or tuple(map(int, r["version"].split("."))) > tuple(
                map(int, cur["version"].split("."))):
            latest[r["id"]] = r
    return latest


def median(xs):
    return round(statistics.median(xs), 1) if xs else None


def main():
    recipes = [load_yaml(p) for p in iter_recipe_files()]
    latest = latest_by_id(recipes)

    grouped = defaultdict(list)
    for p in iter_result_files():
        res = load_yaml(p)
        grouped[(res["recipe_id"], res["content_hash"])].append(res)

    lines = ["# Leaderboard",
             "",
             "_Generated by tools/leaderboard.py — do not hand-edit. "
             "Cross-validation is DERIVED: ≥ 2 distinct contributors at the "
             "same content_hash with every declared test passing at least "
             "once. No universal score — read the dimensions._",
             ""]

    for recipe_id in sorted(latest):
        r = latest[recipe_id]
        chash = r["content_hash"]
        results = grouped.get((recipe_id, chash), [])
        witnesses = {res["contributor_id"] for res in results}

        lines.append(f"## {recipe_id} (v{r['version']})")
        lines.append("")
        lines.append(f"- Model: **{r['model']['name']}** "
                     f"(`{r.get('quant') or '?'}` · {r['model'].get('size_gb')} GB"
                     + (f" · arch {r['model'].get('arch')}" if r['model'].get('arch') else "") + ")")
        lines.append(f"- Objectives: {', '.join(r.get('objectives', {}).get('primary') or []) or '—'}")
        lines.append(f"- Status: `{r['status']}` · witnesses at this hash: "
                     f"**{len(witnesses)}**")

        # capabilities confirmed (from recipe; must be backed by results)
        caps = r.get("harness_compat", {}).get("capabilities_confirmed", {})
        lines.append(f"- Confirmed capabilities: tools={caps.get('tools', False)}, "
                     f"mcp={caps.get('mcp', False)}, "
                     f"vision={caps.get('vision', False)}")

        declared = {t["id"] for t in r.get("tests", [])}
        passed_tests = set()
        if results:
            for res in results:
                for t in res.get("tests", []):
                    if t["result"] == "pass":
                        passed_tests.add(t["id"])

        if len(witnesses) >= MIN_WITNESSES and declared and declared <= passed_tests:
            lines.append(f"- **Cross-validated** (≥ {MIN_WITNESSES} independent "
                         "witnesses, all declared tests passing)")
        elif len(witnesses) >= MIN_WITNESSES:
            lines.append(f"- ≥ {MIN_WITNESSES} witnesses, but NOT all declared "
                         "tests passing — treat with care")
        elif len(witnesses) == 1:
            lines.append("- Unconfirmed — one witness, anecdotal")
        else:
            lines.append("- No results submitted yet")

        # per-test pass rates
        if results:
            rates = defaultdict(lambda: [0, 0])
            statuses = defaultdict(lambda: defaultdict(int))
            for res in results:
                for t in res.get("tests", []):
                    rates[t["id"]][1] += 1
                    if t["result"] == "pass":
                        rates[t["id"]][0] += 1
                    statuses[t["id"]][t["result"]] += 1
            for tid in sorted(rates):
                passed, total = rates[tid]
                extra = " ".join(f"{s}={n}" for s, n in sorted(statuses[tid].items()) if s != "pass")
                lines.append(f"  - test `{tid}`: {passed}/{total} passed"
                             + (f" ({extra})" if extra else ""))

        # dimension medians
        tg = [res.get("metrics", {}).get("tokens_per_sec_tg")
              for res in results if res.get("metrics", {}).get("tokens_per_sec_tg")]
        pp = [res.get("metrics", {}).get("tokens_per_sec_pp")
              for res in results if res.get("metrics", {}).get("tokens_per_sec_pp")]
        qs = sorted({res.get("quant") for res in results} - {None})
        dims = []
        if median(pp) is not None:
            dims.append(f"median prompt {median(pp)} tok/s")
        if median(tg) is not None:
            dims.append(f"median generation {median(tg)} tok/s")
        if qs:
            dims.append(f"quants run: {', '.join(str(q) for q in qs)}")
        if dims:
            lines.append(f"- {'; '.join(dims)}")
        lines.append("")

    out_path = REPO_ROOT / "LEADERBOARD.md"
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
